apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: facebook_chat
  namespace: dev
  labels:
    app: facebook_chat
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: facebook_chat
  template:
    metadata:
      namespace: dev
      labels:
        app: facebook_chat
    spec:
      containers:
        - image: imobility/facebook_imob_chat_integration:latest
          imagePullPolicy: Always
          name: facebook_chat
          ports:
          - containerPort: 80
            protocol: TCP
      imagePullSecrets:
        - name: imobreadonly
---
apiVersion: v1
kind: Service
metadata:
  name: scaffold
  namespace: dev
  labels:
    app: scaffold
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: scaffold
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: facebook_chat
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - api-dev.i-mobility.at
    secretName: imobility-tls
  rules:
  - host: api-dev.i-mobility.at
    http:
      paths:
      - path: '/v1/facebook_chat'
        backend:
          serviceName: facebook_chat
          servicePort: 80
