apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scaffold
  namespace: localdev
  labels:
    app: scaffold
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: scaffold
  template:
    metadata:
      namespace: localdev
      labels:
        app: scaffold
    spec:
      containers:
        - image: imobility/scaffold:latest
          imagePullPolicy: Always
          name: scaffold
          env:
          - name: IMOB_ES_SERVERS
            value: db-dev.imob.dk
          ports:
          - containerPort: 80
            protocol: TCP
      imagePullSecrets:
        - name: imobreadonly
---
apiVersion: v1
kind: Service
metadata:
  name: scaffold
  namespace: localdev
  labels:
    app: scaffold
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30201
  selector:
    app: scaffold
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scaffold
  namespace: localdev
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - api-local.i-mobility.at
    secretName: imobility-tls
  rules:
  - host: api-local.i-mobility.at
    http:
      paths:
      - path: '/v1/scaffold'
        backend:
          serviceName: scaffold
          servicePort: 80
